services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: justeat_frontend_angular_prod
    restart: unless-stopped
    expose:
      - "4200"
    environment:
      - NODE_ENV=production
    networks:
      - justeat_network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.allownonrunning=true"
      - "traefik.http.routers.justeat-angular.rule=Host(`justeat-angular.swiftapp.ch`)"
      - "traefik.http.routers.justeat-angular.entrypoints=websecure"
      - "traefik.http.routers.justeat-angular.tls.certresolver=letsencrypt"
      - "traefik.http.routers.justeat-angular.middlewares=sablier-justeat@file"
      - "traefik.http.services.justeat-angular.loadbalancer.server.port=4200"
      - "sablier.enable=true"
      - "sablier.group=justeat"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:4200/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  justeat_network:
    external: true
  traefik:
    external: true
